// <auto-generated />
namespace AspNetWebApiBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_virual_posts_to_cat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_virual_posts_to_cat));
        
        string IMigrationMetadata.Id
        {
            get { return "201705111326137_add_virual_posts_to_cat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
