// <auto-generated />
namespace AspNetWebApiBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_comment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_comment));
        
        string IMigrationMetadata.Id
        {
            get { return "201704021413051_add_comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
