// <auto-generated />
namespace AspNetWebApiBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_age_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_age_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201708061147464_update_age_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
